import dotenv from 'dotenv';
import express from 'express';
import { Pool } from 'pg';

dotenv.config({ path: '.env.local' });
dotenv.config();

const app = express();
const port = Number(process.env.PORT || 8787);
const databaseUrl = process.env.DATABASE_URL;

app.use(express.json());
app.use((_, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  next();
});

const pool = databaseUrl
  ? new Pool({
      connectionString: databaseUrl,
      ssl: { rejectUnauthorized: false },
    })
  : null;

async function ensureDatabaseReady() {
  if (!pool) {
    throw new Error('DATABASE_URL is missing. Add it to .env.local before starting the server.');
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS inquiries (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      course TEXT NOT NULL,
      message TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
}

app.get('/api/health', async (_req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const result = await pool.query('SELECT NOW() AS now');
    return res.json({ ok: true, connectedAt: result.rows[0]?.now });
  } catch (error) {
    console.error('Database health check failed:', error);
    return res.status(500).json({ ok: false, error: 'Database connection failed.' });
  }
});

app.post('/api/inquiries', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { name, phone, course, message } = req.body as {
      name?: string;
      phone?: string;
      course?: string;
      message?: string;
    };

    if (!name || !phone || !course) {
      return res.status(400).json({ ok: false, error: 'Name, phone, and course are required.' });
    }

    await pool.query(
      'INSERT INTO inquiries (name, phone, course, message) VALUES ($1, $2, $3, $4)',
      [name, phone, course, message ?? '']
    );

    return res.status(201).json({ ok: true, message: 'Inquiry saved successfully.' });
  } catch (error) {
    console.error('Failed to save inquiry:', error);
    return res.status(500).json({ ok: false, error: 'Could not save inquiry right now.' });
  }
});

ensureDatabaseReady()
  .then(() => {
    app.listen(port, () => {
      console.log(`Supabase API server running on http://localhost:${port}`);
    });
  })
  .catch((error) => {
    console.error('Server startup failed:', error);
    process.exit(1);
  });
