import dotenv from 'dotenv';
import express from 'express';
import { Pool } from 'pg';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

dotenv.config({ path: '.env.local' });
dotenv.config();

const app = express();
const port = Number(process.env.PORT || 8787);
const databaseUrl = process.env.DATABASE_URL;

app.use(express.json());
app.use((_, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  next();
});

// Serve static files from dist folder
app.use(express.static(path.join(__dirname, 'dist')));

const pool = databaseUrl
  ? new Pool({
      connectionString: databaseUrl,
      ssl: { rejectUnauthorized: false },
    })
  : null;

async function ensureDatabaseReady() {
  if (!pool) {
    throw new Error('DATABASE_URL is missing. Add it to .env.local before starting the server.');
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'student',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS courses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      instructor_id BIGINT REFERENCES users(id),
      subject TEXT NOT NULL,
      level TEXT,
      duration_hours INT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS materials (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      content TEXT,
      type TEXT,
      url TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS tests (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      description TEXT,
      total_questions INT,
      duration_minutes INT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS test_responses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      test_id BIGINT REFERENCES tests(id) ON DELETE CASCADE,
      user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
      score INT,
      total_marks INT,
      completed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS enrollments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
      course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
      enrolled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(user_id, course_id)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS inquiries (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      course TEXT NOT NULL,
      message TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
}

app.get('/api/health', async (_req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const result = await pool.query('SELECT NOW() AS now');
    return res.json({ ok: true, connectedAt: result.rows[0]?.now });
  } catch (error) {
    console.error('Database health check failed:', error);
    return res.status(500).json({ ok: false, error: 'Database connection failed.' });
  }
});

app.post('/api/inquiries', async (req, res) => {
  try {
    const { name, phone, course, message } = req.body as {
      name?: string;
      phone?: string;
      course?: string;
      message?: string;
    };

    if (!name || !phone || !course) {
      return res.status(400).json({ ok: false, error: 'Name, phone, and course are required.' });
    }

    if (pool) {
      // Database is available, save to database
      await pool.query(
        'INSERT INTO inquiries (name, phone, course, message) VALUES ($1, $2, $3, $4)',
        [name, phone, course, message ?? '']
      );
    } else {
      // Development mode without database - log inquiry to console
      console.log('📝 New Inquiry (Development Mode - No DB):', {
        name,
        phone,
        course,
        message,
        timestamp: new Date().toISOString(),
      });
    }

    return res.status(201).json({ ok: true, message: 'Inquiry saved successfully.' });
  } catch (error) {
    console.error('Failed to save inquiry:', error);
    return res.status(500).json({ ok: false, error: 'Could not save inquiry right now.' });
  }
});

// Users API
app.post('/api/users', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { email, name, role } = req.body as {
      email?: string;
      name?: string;
      role?: string;
    };

    if (!email || !name) {
      return res.status(400).json({ ok: false, error: 'Email and name are required.' });
    }

    const result = await pool.query(
      'INSERT INTO users (email, name, role) VALUES ($1, $2, $3) RETURNING *',
      [email, name, role ?? 'student']
    );

    return res.status(201).json({ ok: true, data: result.rows[0] });
  } catch (error) {
    console.error('Failed to create user:', error);
    return res.status(500).json({ ok: false, error: 'Could not create user.' });
  }
});

app.get('/api/users', async (_req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const result = await pool.query('SELECT * FROM users ORDER BY created_at DESC');
    return res.json({ ok: true, data: result.rows });
  } catch (error) {
    console.error('Failed to fetch users:', error);
    return res.status(500).json({ ok: false, error: 'Could not fetch users.' });
  }
});

// Courses API
app.post('/api/courses', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { name, description, subject, level, duration_hours } = req.body as any;

    if (!name || !subject) {
      return res.status(400).json({ ok: false, error: 'Name and subject are required.' });
    }

    const result = await pool.query(
      'INSERT INTO courses (name, description, subject, level, duration_hours) VALUES ($1, $2, $3, $4, $5) RETURNING *',
      [name, description, subject, level, duration_hours]
    );

    return res.status(201).json({ ok: true, data: result.rows[0] });
  } catch (error) {
    console.error('Failed to create course:', error);
    return res.status(500).json({ ok: false, error: 'Could not create course.' });
  }
});

app.get('/api/courses', async (_req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const result = await pool.query('SELECT * FROM courses ORDER BY created_at DESC');
    return res.json({ ok: true, data: result.rows });
  } catch (error) {
    console.error('Failed to fetch courses:', error);
    return res.status(500).json({ ok: false, error: 'Could not fetch courses.' });
  }
});

// Materials API
app.post('/api/materials', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { course_id, title, content, type, url } = req.body as any;

    if (!course_id || !title) {
      return res.status(400).json({ ok: false, error: 'Course ID and title are required.' });
    }

    const result = await pool.query(
      'INSERT INTO materials (course_id, title, content, type, url) VALUES ($1, $2, $3, $4, $5) RETURNING *',
      [course_id, title, content, type, url]
    );

    return res.status(201).json({ ok: true, data: result.rows[0] });
  } catch (error) {
    console.error('Failed to create material:', error);
    return res.status(500).json({ ok: false, error: 'Could not create material.' });
  }
});

app.get('/api/courses/:courseId/materials', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { courseId } = req.params;
    const result = await pool.query('SELECT * FROM materials WHERE course_id = $1 ORDER BY created_at DESC', [courseId]);
    return res.json({ ok: true, data: result.rows });
  } catch (error) {
    console.error('Failed to fetch materials:', error);
    return res.status(500).json({ ok: false, error: 'Could not fetch materials.' });
  }
});

// Tests API
app.post('/api/tests', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { course_id, title, description, total_questions, duration_minutes } = req.body as any;

    if (!course_id || !title) {
      return res.status(400).json({ ok: false, error: 'Course ID and title are required.' });
    }

    const result = await pool.query(
      'INSERT INTO tests (course_id, title, description, total_questions, duration_minutes) VALUES ($1, $2, $3, $4, $5) RETURNING *',
      [course_id, title, description, total_questions, duration_minutes]
    );

    return res.status(201).json({ ok: true, data: result.rows[0] });
  } catch (error) {
    console.error('Failed to create test:', error);
    return res.status(500).json({ ok: false, error: 'Could not create test.' });
  }
});

app.get('/api/courses/:courseId/tests', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { courseId } = req.params;
    const result = await pool.query('SELECT * FROM tests WHERE course_id = $1 ORDER BY created_at DESC', [courseId]);
    return res.json({ ok: true, data: result.rows });
  } catch (error) {
    console.error('Failed to fetch tests:', error);
    return res.status(500).json({ ok: false, error: 'Could not fetch tests.' });
  }
});

// Enrollments API
app.post('/api/enrollments', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { user_id, course_id } = req.body as any;

    if (!user_id || !course_id) {
      return res.status(400).json({ ok: false, error: 'User ID and course ID are required.' });
    }

    const result = await pool.query(
      'INSERT INTO enrollments (user_id, course_id) VALUES ($1, $2) RETURNING *',
      [user_id, course_id]
    );

    return res.status(201).json({ ok: true, data: result.rows[0] });
  } catch (error) {
    console.error('Failed to create enrollment:', error);
    return res.status(500).json({ ok: false, error: 'Could not create enrollment.' });
  }
});

app.get('/api/users/:userId/courses', async (req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const { userId } = req.params;
    const result = await pool.query(
      `SELECT c.* FROM courses c 
       JOIN enrollments e ON c.id = e.course_id 
       WHERE e.user_id = $1 
       ORDER BY c.created_at DESC`,
      [userId]
    );
    return res.json({ ok: true, data: result.rows });
  } catch (error) {
    console.error('Failed to fetch user courses:', error);
    return res.status(500).json({ ok: false, error: 'Could not fetch user courses.' });
  }
});

// Inquiries API - Get all
app.get('/api/inquiries', async (_req, res) => {
  try {
    if (!pool) {
      return res.status(503).json({ ok: false, error: 'DATABASE_URL is missing.' });
    }

    const result = await pool.query('SELECT * FROM inquiries ORDER BY created_at DESC');
    return res.json({ ok: true, data: result.rows });
  } catch (error) {
    console.error('Failed to fetch inquiries:', error);
    return res.status(500).json({ ok: false, error: 'Could not fetch inquiries.' });
  }
});

// SPA Fallback middleware - route all non-API requests to index.html
app.use((req, res, next) => {
  if (req.method === 'GET' && !req.path.startsWith('/api') && !req.path.includes('.')) {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'), (err) => {
      if (err) {
        res.status(404).json({ ok: false, error: 'Not found' });
      }
    });
  } else {
    next();
  }
});

ensureDatabaseReady()
  .then(() => {
    app.listen(port, () => {
      console.log(`Supabase API server running on http://localhost:${port}`);
    });
  })
  .catch((error) => {
    console.warn('Database connection failed:', error.message);
    console.warn('Starting server in development mode without database...');
    app.listen(port, () => {
      console.log(`Development API server running on http://localhost:${port} (no database)`);
    });
  });
